matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"

before_install:
    - eval "${MATRIX_EVAL}"

language: c
compiler:
  - clang
script: make -f Makefile_Linux
deploy:
  provider: s3
  access_key_id: $SKEY
  secret_access_key: $SSKEY
  bucket: "hjwasm"
  skip_cleanup: true
